### ISSUE TITLE
Erc20 in vesting 

### ISSUE THREAD

**Issue by Shantaramm** [AbdelStark/token-vesting-contracts#82]
hello! I have a little question.
Why do we use ERC20.sol in the vesting.sol contract and not IERC20.sol?

**Comment by abdelhamidbakhta** [comment]
good point, we should use the interface. feel free to submit a PR if you want

**Comment by Shantaramm** [comment]
> good point, we should use the interface. feel free to submit a PR if you want

Cool! But if you implement IERC20 here, then the SafeTransferLib.sol library may not work, since it accepts ERC20 as input
![image](https://github.com/abdelhamidbakhta/token-vesting-contracts/assets/56877750/44845acb-e57c-4c53-868b-ff752afd8dcd)

**Comment by Bocoi501** [comment]
Sol
3hx5CZJeM67NHJ2WwqaMtPcu5oA6RruRpqYHLA3k1Hc9
